const ACTIONS = {
	BONUS       : {
		GET : {
			FETCHING : 'GET_BONUS_FETCHING',
			SUCCESS  : 'GET_BONUS_SUCCESS',
			FAILURE  : 'GET_BONUS_FAILURE',
		}
	},
	LIVE        : {
		GET                     : {
			FACTORS        : "LIVE_GET_FACTORS",
			ADDITIONAL     : "LIVE_GET_ADDITIONAL",
			REQUEST        : "LIVE_GET_REQUEST",
			SUCCESS        : "LIVE_GET_SUCCESS",
			FAILURE        : "LIVE_GET_FAILURE",
			UPDATE         : "LIVE_GET_UPDATE",
			UPDATE_FACTORS : "LIVE_GET_UPDATE_FACTORS"
		},
		ADD_EVENT_TO_WATCH      : "LIVE_ADD_EVENT_TO_WATCH",
		DELETE_EVENT_FROW_WATCH : "LIVE_DELETE_EVENT_FROM_WATCH",
		GET_NOW                 : "LIVE_GET_NOW",
		GET_SPORTS              : "LIVE_GET_SPORTS",
		TOGGLE_SPORT            : "LIVE_TOGGLE_SPORT",
		TOGGLE_LEAGUE           : "LIVE_TOGGLE_LEAGUE",
		GET_LEAGUES             : {
			REQUEST : "LIVE_GET_LEAGUES_REQUEST",
			SUCCESS : "LIVE_GET_LEAGUES_SUCCESS"
		},
		GET_EVENTS              : {
			REQUEST : "LIVE_GET_EVENTS_REQUEST",
			SUCCESS : "LIVE_GET_EVENTS_SUCCESS",
		},
		INIT_ELEMENTS_BY_STAR   : "INIT_ELEMENTS_BY_STAR",
		GET_FACTOR_BY_ID        : {
			REQUEST : "LIVE_GET_FACTOR_BY_ID_REQUEST",
			SUCCESS : "LIVE_GET_FACTOR_BY_ID_SUCCESS",
			FAILURE : "LIVE_GET_FACTOR_BY_ID_FAILURE"
		},
		GET_BY_ID               : {
			REQUEST     : "LIVE_GET_BY_ID_REQUEST",
			SUCCESS     : "LIVE_GET_BY_ID_SUCCESS",
			FAILURE     : "LIVE_GET_BY_ID_FAILURE",
			FULL_FACTOR : {
				REQUEST : "LIVE_GET_BY_ID_FULL_FACTOR_REQUEST",
				SUCCESS : "LIVE_GET_BY_ID_FULL_FACTOR_SUCCESS",
				FAILURE : "LIVE_GET_BY_ID_FULL_FACTOR_FAILURE",
			},
			CLEAR_STATE : "LIVE_GET_BY_ID_CLEAR_STATE"
		},
		EVENT                   : {
			RESULTS : {
				UPDATE : "LIVE_EVENT_RESULTS_UPDATE"
			}
		},
		UPDATE                  : "LIVE_UPDATE",
		TOOLBAR                 : {
			SELECT_SPORT       : "LIVE_TOOLBAR_SELECT_SPORT",
			TOGGLE_IS_FAVORITE : "LIVE_TOOLBAR_TOGGLE_IS_FAVORITE",
		}
	},
	LINE        : {
		GET_SPORTS       : "LINE_GET_SPORTS",
		GET_LEAGUES      : {
			REQUEST : "LINE_GET_LEAGUES_REQUEST",
			SUCCESS : "LINE_GET_LEAGUES_SUCCESS"
		},
		GET_EVENTS       : {
			REQUEST : "LINE_GET_EVENTS_REQUEST",
			SUCCESS : "LINE_GET_EVENTS_SUCCESS",
		},
		GET_FACTOR_BY_ID : {
			REQUEST : "LINE_GET_FACTOR_BY_ID_REQUEST",
			SUCCESS : "LINE_GET_FACTOR_BY_ID_SUCCESS",
			FAILURE : "LINE_GET_FACTOR_BY_ID_FAILURE"
		},
		TOGGLE_SPORT     : "LINE_TOGGLE_SPORT",
		TOGGLE_LEAGUE    : "LINE_TOGGLE_LEAGUE",

		GET_SETTINGS              : "LINE_GET_SETTINGS",
		GET_LINE                  : "LINE_GET_LINE",
		GET_POPULAR               : "LINE_GET_POPULAR",
		FETCHING                  : "LINE_FETCHING",
		POP_FETCHING              : "POP_FETCHING",
		LINE_SELECT               : "LINE_SELECT",
		SELECT_SPORT              : "SELECT_SPORT",
		GET_LINE_DATA             : "GET_LINE_DATA",
		SELECT_FETCHING           : "SELECT_FETCHING",
		SELECT_SPORT_LINE         : "SELECT_SPORT_LINE",
		RESET_SELECTED_SPORT_LINE : "RESET_SELECTED_SPORT_LINE",
		MAIN_GET_LEAGUE           : "MAIN_GET_LEAGUE",
		INIT_LINE_SPORT           : "INIT_LINE_SPORT",

		MAIN_LINE_SELECT              : "MAIN_LINE_SELECT",
		MAIN_FETCHING                 : "MAIN_FETCHING",
		MAIN_SHOW_ALL                 : "MAIN_SHOW_ALL",
		MAIN_SHOW_SELECTED            : "MAIN_SHOW_SELECTED",
		MAIN_GET_LINE                 : "MAIN_GET_LINE",
		MAIN_GET_LINE_DATA            : "MAIN_GET_LINE_DATA",
		MAIN_GET_POPULAR              : "MAIN_GET_POPULAR",
		MAIN_GET_LINE_DATA_AND_UPDATE : "MAIN_GET_LINE_DATA_AND_UPDATE",
	},
	RESULT      : {
		GET_LIVE                   : "RESULT_GET_LIVE",
		GET_LINE                   : "RESULT_GET_LINE",
		FETCHING                   : "RESULT_FETCHING",
		CHANGE_SELECTED_SPORT      : "CHANGE_SELECTED_SPORT",
		RESET_ALL_SELECTED_FILTERS : "RESET_ALL_SELECTED_FILTERS",
		ALL_CHECKED_FILTERS        : "ALL_CHECKED_FILTERS",
		SHOW_SELECTED_SPORTS       : "SHOW_SELECTED_SPORTS",
		TOGGLE_ADD                 : "TOGGLE_ADD",
		INIT_STATE                 : "INIT_STATE",

		RESET_FILTER         : "RESET_FILTER",
		CHANGE_CHECKED_SPORT : "CHANGE_CHECKED_SPORT",
		CHANGE_CHECKED_DATA  : "CHANGE_CHECKED_DATA",
		CHANGE_SELECTED_DATA : "CHANGE_SELECTED_DATA",

	},
	USER        : {
		GET_INFO           : "GET_INFO",
		SET_IMAGES         : "SET_IMAGES",
		LOGIN              : "USER_LOGIN",
		LOGOUT             : "USER_LOGOUT",
		CASHBACK           : {
			FETCHING    : "CASHBACK_FETCHING",
			GET_SUCCESS : "CASHBACK_GET_SUCCESS",
			FAILURE_GET : "CASHBACK_GET_FAILURE",
			PAY_SUCCESS : "CASHBACK_PAY_SUCCESS",
			FAILURE_PAY : "CASHBACK_PAY_FAILURE",
		},
		UPLOAD_PASSPORT    : {
			REQUEST : 'UPLOAD_PASSPORT_REQUEST',
			SUCCESS : 'UPLOAD_PASSPORT_SUCCESS',
			FAILURE : 'UPLOAD_PASSPORT_FAILURE'
		},
		SAVE_INFO          : "SAVE_INFO",
		CHANGE_CHECKED     : "CHANGE_CHECKED",
		SEND_COMMENT       : "UPLOAD_PASSPORT",
		HISTORY_SESSION    : "HISTORY_SESSION",
		HISTORY_OPERATIONS : "HISTORY_OPERATIONS",
		HISTORY_BONUS      : "HISTORY_BONUS",
	},
	COUPON      : {
		FETCHING             : "COUPON_FETCHING",
		UPDATE               : "COUPON_UPDATE",
		CHANGE_LIVE_OPT      : "COUPON_CHANGE_LIVE_OPT",
		ERROR                : "COUPON_ERROR",
		GET_OPENED_BETS_LIVE : "COUPON_GET_OPENED_BETS_LIVE",
		GET_OPENED_BETS_LINE : "COUPON_GET_OPENED_BETS_LINE"
	},
	ONECLICK    : {
		TOGGLE           : "ONECLICK_TOGGLE",
		CHANGE_AMOUNT    : "ONECLICK_CHANGE_AMOUNT",
		START_PROCESSING : "ONECLICK_START_PROCESSING",
		STOP_PROCESSING  : "ONECLICK_STOP_PROCESSING",
	},
	PAYMENTS    : {
		GET_HISTORY : "PAYMENTS_GET_HISTORY",
		CANCEL      : "PAYMENTS_CANCEL"
	},
	NEWS        : {
		FETCHING      : "NEWS_FETCHING",
		UPDATE        : "NEWS_UPDATE",
		RECEIVE_PROPS : "RECEIVE_PROPS",
	},
	DATA        : {
		COUPON_FACTORS : "DATA_COUPON_FACTORS"
	},
	VIDEO_MODAL : {
		UPDATE : "VIDEO_MODAL_UPDATE"
	},
	AUTH        : {
		UPDATE    : "AUTH_UPDATE",
		IS_ONLINE : "AUTH_IS_ONLINE"
	},
	CASHOUT     : {
		CARD      : {
			GET_CARD_LIST : "GET_CARD_LIST",
			ENTER_AMOUNT  : "CARD_ENTER_AMOUNT",
			SELECT_CARD   : "SELECT_CARD",
			CARD_FAILURE  : 'CARD_FAILURE',
			SEND_ORDER    : {
				REQUEST : 'CARD_SEND_ORDER_REQUEST',
				SUCCESS : 'CARD_SEND_ORDER_SUCCESS',
				FAILURE : 'CARD_SEND_ORDER_FAILURE'
			}
		},
		CASH      : {
			LOAD_INFO      : "CASH_LOAD_INFO",
			VALID_FAILURE  : "VALID_FAILURE",
			ENTER_AMOUNT   : 'CASH_ENTER_AMOUNT',
			SELECT_ADDRESS : "SELECT_ADDRESS",
			SEND_ORDER     : {
				REQUEST : 'CASH_SEND_ORDER_REQUEST',
				SUCCESS : 'CASH_SEND_ORDER_SUCCESS',
				FAILURE : 'CASH_SEND_ORDER_FAILURE'
			}
		},
		BELINVEST : {
			ENTER_PHONE   : 'BELINVEST_ENTER_PHONE',
			ENTER_AMOUNT  : 'BELINVEST_ENTER_AMOUNT',
			VALID_FAILURE : 'BELINVEST_VALID_FAILURE',
			SEND_ORDER    : {
				REQUEST : 'BELINVEST_SEND_ORDER_REQUEST',
				SUCCESS : 'BELINVEST_SEND_ORDER_SUCCESS',
				FAILURE : 'BELINVEST_SEND_ORDER_FAILURE'
			}
		},
		MOBILE    : {
			ENTER_AMOUNT    : 'MOBILE_ENTER_AMOUNT',
			ENTER_PHONE     : 'MOBILE_ENTER_PHONE',
			VALID_FAILURE   : 'MOBILE_VALID_FAILURE',
			SELECT_PROVIDER : 'MOBILE_SELECT_PROVIDER',
			SEND_ORDER      : {
				REQUEST : 'MOBILE_SEND_ORDER_REQUEST',
				SUCCESS : 'MOBILE_SEND_ORDER_SUCCESS',
				FAILURE : 'MOBILE_SEND_ORDER_FAILURE'
			}
		}
	},
	SYSTEM      : {
		CHANGE_LANGUAGE            : "CHANGE_LANGUAGE",
		CHANGE_THEME               : "SYSTEM_CHANGE_THEME",
		CHANGE_BALANCE             : "CHANGE_BALANCE",
		CHANGE_DISPLAY_KOEFF       : "CHANGE_DISPLAY_KOEFF",
		CHANGE_DISPLAY_STYLE_KOEFF : "CHANGE_DISPLAY_STYLE_KOEFF",
		LOCALIZATION               : "SYSTEM_LOCALIZATION"
	},
	SERVICE     : {
		GET_STATUS : "SERVICE_GET_STATUS"
	},
	FACTORS     : {
		REQUEST : "FACTORS_REQUEST",
		SUCCESS : "FACTORS_SUCCESS",
		FAILURE : "FACTORS_FAILURE"
	},
	FAVORITE    : {
		ADD    : "FAVORITE_ADD",
		REMOVE : "FAVORITE_REMOVE",
		TOGGLE : "FAVORITE_TOGGLE"
	},
	SOCKET      : {
		INIT          : "SOCKET_INIT",
		CONNECT       : "SOCKET_CONNECT",
		CONNECTING    : "SOCKET_CONNECTING",
		DISCONNECTING : "SOCKET_DISCONNECTING",
		DISCONNECT    : "SOCKET_DISCONNECT",
		MESSAGE       : "SOCKET_MESSAGE",
		GET_LIVE      : "SOCKET_GET_LIVE",
		CLOSE         : "SOCKET_CLOSE",
		ERROR         : "SOCKET_ERROR"
	}
};

export default ACTIONS;